/*step1*/

export const CHANGE_ERR_MAIL_TEXT = 'CHANGE_ERR_MAIL_TEXT';
export const SET_USER_DATA = 'SET_USER_DATA';


export const SET_STEP1_FORMS_REQUEST = 'SET_STEP1_FORMS_REQUEST';
export const SET_STEP1_FORMS_SUCCESS = 'SET_STEP1_FORMS_SUCCESS';
export const SET_STEP1_FORMS_FAILURE = 'SET_STEP1_FORMS_FAILURE';
/*Step2*/

export const SET_IMG_AVATAR_FILE = 'SET_IMG_AVATAR_FILE';
export const SET_IMG_AVATAR_URL = 'SET_IMG_AVATAR_URL';
export const SET_IMG_AVATAR_LOAD = 'SET_IMG_AVATAR_LOAD';

/*Step3*/
export const SET_IMG_DOC_FILE = 'SET_IMG_DOC_FILE';
export const SET_PHOTO_DOC = 'SET_PHOTO_DOC';
export const REMOVE_PHOTO_DOC = 'REMOVE_PHOTO_DOC';
export const SET_PHOTO_DOC_REQUEST = 'SET_PHOTO_DOC_REQUEST';
export const SET_PHOTO_DOC_SUCCESS = 'SET_PHOTO_DOC_SUCCESS';
export const SET_PHOTO_DOC_FAILURE = 'SET_PHOTO_DOC_FAILURE';

/*For_all_steps*/

export const CHANGE_BUTTON_LOAD = 'CHANGE_BUTTON_LOAD';
export const CHANGE_REDIRECT = 'CHANGE_REDIRECT';
export const CHANGE_WARNING_TEXT = 'CHANGE_WARNING_TEXT';

export const SET_STEP1 = 'SET_STEP1';
export const SET_STEP2 = 'SET_STEP2';

export const SET_REG_BUTTON_ACTIVE1 = 'SET_REG_BUTTON_ACTIVE1';
export const SET_REG_BUTTON_ACTIVE2 = 'SET_REG_BUTTON_ACTIVE2';
export const SET_REG_BUTTON_ACTIVE3 = 'SET_REG_BUTTON_ACTIVE3';

/*Submits*/

export const SET_STEP3 = 'SET_STEP3';
export const SET_STEP3_REQUEST = 'SET_STEP3_REQUEST';
export const SET_STEP3_SUCCESS = 'SET_STEP3_SUCCESS';
export const SET_STEP3_FAILURE = 'SET_STEP3_FAILURE';

export const UPLOAD_AVATAR_REQUEST = 'UPLOAD_AVATAR_REQUEST';
export const UPLOAD_AVATAR_SUCCESS = 'UPLOAD_AVATAR_SUCCESS';
export const UPLOAD_AVATAR_FAILURE = 'UPLOAD_AVATAR_FAILURE';

export const FINISH_REG_REQUEST = "FINISH_REG_REQUEST";
export const FINISH_REG_SUCCESS = "FINISH_REG_SUCCESS";
export const FINISH_REG_FAILURE = "FINISH_REG_FAILURE";

export const SET_FINISH_REG = "SET_FINISH_REG";

export const CHANGE_DOC_ITEM = 'CHANGE_DOC_ITEM';

/* Error */
